service: trivial-react-login

provider:
    name: aws
    region: ap-southeast-2
    runtime: provided
    stage: prod
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
#    console:
#        handler: bin/console
#        timeout: 120 # in seconds
#        layers:
#            - ${bref:layer.php-73} # PHP
#            - ${bref:layer.console} # The "console" layer

Globals:
    Function:
        Environment:
            Variables:
                APP_ENV: prod